title: Marla Eisman # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: |
  I am a MS/PhD student at the University of California, Berkeley. I research model predictive control and machine learning with the [MPC lab](https://sites.google.com/berkeley.edu/mpc-lab). I received my bachelor's degree in mechanical engineering from the University of Florida (UF) in December 2024. During my undergraduate education, I was the Lead Engineer at Gator Motorsports, a researcher in UFâ€™s Nonlinear Controls and Robotics Lab and the Cognition, Action, and Perception of Speech Lab, and completed internships at SpaceX, Tesla, and Vatn Systems. I also volunteered with the Society of Women Engineers and Haven Hospice.

  Contact: marlaeism6@gmail.com
  Linkedin: https://www.linkedin.com/in/marla-eisman-017ba5200/
  My CV: /cv/

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

github:
  is_project_page: false